MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarahTizzard_WEBD3000_MyTunes_MVC.Models
{
    public partial class Artist
    {
        public Artist()
        {
            Albums = new HashSet<Album>();
        }

        public int ArtistId { get; set; }

        [Required]
        [RegularExpression(@"^.{3,50}$", ErrorMessage = "Artist name must be between 3 and 50 characters.")]
        //[Remote("doesArtistExist", "Artist", HttpMethod = "POST", ErrorMessage = "Artist name already exists")]
        public string Name { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

       // public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
       // public virtual ICollection<Track> Tracks { get; set; }
    }
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SarahTizzard_WEBD3000_MyTunes_MVC.DAL;
using SarahTizzard_WEBD3000_MyTunes_MVC.Models;
using SarahTizzard_WEBD3000_MyTunes_MVC.ViewModels;
using PagedList;
using System.Web.Security;
using System.Threading.Tasks;
using System.Data.Entity.Infrastructure;

namespace SarahTizzard_WEBD3000_MyTunes_MVC.Controllers
{
    public class ArtistController : Controller
    {
        private MyTunesContext db = new MyTunesContext();

        // GET: Artist
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page, int? id, int? albumId, int? artistPage, int? albumPage, int? trackPage)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
            int artistPageNumber = (artistPage ?? 1);
            int albumPageNumber = (albumPage ?? 1);
            int trackPageNumber = (trackPage ?? 1);

            var viewModel = new ArtistIndexData();
            viewModel.Artists = db.Artists
                .Include(a => a.Albums)
               // .Include(a => a.Tracks.Select(t => t.Name))
                .OrderBy(a => a.Name).ToPagedList(artistPageNumber, 5);

            if (id != null)
            {
                ViewBag.ArtistId = id.Value;
                viewModel.Albums = viewModel.Artists.Where(
                    i => i.ArtistId == id.Value).Single().Albums.ToList();
            }

            if (albumId != null)
            {
                ViewBag.AlbumId = albumId.Value;
                viewModel.Tracks = viewModel.Albums.Where(
                    x => x.AlbumId == albumId).Single().Tracks.ToList();
            }

           
            return View(viewModel);


            //ViewBag.IdSortParm = sortOrder == "ArtistId" ? "artistId_desc" : "ArtistId";

            //if (searchString != null)
            //{
            //    page = 1;
            //}
            //else
            //{
            //    searchString = currentFilter;
            //}

            ////ViewBag.CurrentFilter = searchString;

            ////var artists = from a in db.Artists
            ////             select a;

            //if (!String.IsNullOrEmpty(searchString))
            //{
            //    viewModel.Artists = viewModel.Artists.Where(a => a.Name.Contains(searchString)).ToPagedList(artistPageNumber, 5);
            //}
            //switch (sortOrder)
            //{
            //    case "name_desc":
            //        viewModel.Artists = viewModel.Artists.OrderByDescending(a => a.Name).ToPagedList(artistPageNumber, 5);
            //        break;
            //    case "Name":
            //        viewModel.Artists = viewModel.Artists.OrderBy(a => a.Name).ToPagedList(artistPageNumber, 5);
            //        break;
            //    //case "artistId_desc":
            //    //    artists = artists.OrderByDescending(a => a.ArtistId);
            //    //    break;
            //    //case "ArtistId":
            //    //    artists = artists.OrderBy(a => a.ArtistId);
            //    //    break;
            //    default:
            //        viewModel.Artists = artists.OrderBy(a => a.Name).ToPagedList(artistPageNumber, 5);
            //        break;
            //}

            //int pageSize = 25;
            //int pageNumber = (page ?? 1);
            //return View(artists.ToPagedList(pageNumber, pageSize));
            //return View(tracks.ToList());
        }
       

        // GET: Artist/Details/5
        public ActionResult Details(int? id, int? page)
        {
            ArtistDetailsData data = new ArtistDetailsData();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Artist artist = db.Artists.Find(id);
            data.Artist = artist;

            if (artist == null)
            {
                return HttpNotFound();
            }


            var albums = db.Albums.Where(i => i.ArtistId == id).OrderBy(a => a.Title);
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            data.Albums = albums.ToPagedList(pageNumber, pageSize);
            return View(data);
        }

        // GET: Artist/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artist/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ArtistId,Name")] Artist artist)
        {
            try
            {
                bool doesItExist = db.Artists.Any(anyArtist => anyArtist.Name.Equals(artist.Name));
                if (!doesItExist)
                {

                    if (ModelState.IsValid)
                    {
                        db.Artists.Add(artist);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(artist);
                }
                else
                {
                    Response.Write("<div class='error'>Artist already exists</div>");
                    return View();
                }
            }
            catch
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                return View();
            }
            
        }

        // GET: Artist/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artist/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, byte[] rowVersion)
        {
            string[] fieldsToBind = new string[] { "ArtistId", "Name" };

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artistToUpdate = await db.Artists.FindAsync(id);
            if (artistToUpdate == null)
            {
                Artist deletedArtist = new Artist();
                TryUpdateModel(deletedArtist, fieldsToBind);
                ModelState.AddModelError(string.Empty,
                    "Unable to save changes. The artist was deleted by another user.");
                ViewBag.AlbumID = new SelectList(db.Albums, "AlbumId", "Title", deletedArtist.ArtistId);
                return View(deletedArtist);
            }

            if (TryUpdateModel(artistToUpdate, fieldsToBind))
            {
                try
                {
                    db.Entry(artistToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    await db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var entry = ex.Entries.Single();
                    var clientValues = (Artist)entry.Entity;
                    var databaseEntry = entry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError(string.Empty,
                            "Unable to save changes. The artist was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Artist)databaseEntry.ToObject();

                        if (databaseValues.Name != clientValues.Name)
                            ModelState.AddModelError("Name", "Current value: "
                                + databaseValues.Name);                        
                        if (databaseValues.ArtistId != clientValues.ArtistId)
                            ModelState.AddModelError("ArtistId", "Current value: "
                                + db.Albums.Find(databaseValues.ArtistId).Title);
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                            + "was modified by another user after you got the original value. The "
                            + "edit operation was canceled and the current values in the database "
                            + "have been displayed. If you still want to edit this record, click "
                            + "the Save button again. Otherwise click the Back to List hyperlink.");
                        artistToUpdate.RowVersion = databaseValues.RowVersion;
                    }
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }

            return View(artistToUpdate);
        }


        // GET: Artist/Delete/5
        public async Task<ActionResult> Delete(int? id, bool? concurrencyError)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Create.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Artist

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Delete.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Artist

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (@ViewBag.ConcurrencyErrorMessage != null)
{
    <p class="error">@ViewBag.ConcurrencyErrorMessage</p>

}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ArtistId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Details.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.ViewModels.ArtistDetailsData
@using PagedList.Mvc;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(modelItem => modelItem.Artist)


        </dt>

        <dd>
            @Html.DisplayFor(modelItem => modelItem.Artist.Name)


        </dd>
        <dt>
            Albums
        </dt>

        @foreach (var item in Model.Albums)
        {

            <dd>
                @Html.DisplayFor(modelItem => item.Title)
            </dd>
        }
    </dl>
</div>

Page @(Model.Albums.PageCount < Model.Albums.PageNumber ? 0 : Model.Albums.PageNumber) of @Model.Albums.PageCount

@Html.PagedListPager(Model.Albums, page => Url.Action("Details", new { page }))
<br />

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Artist.ArtistId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Edit.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Artist

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ArtistId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Index - preRelatedData.cshtml
@*@model IEnumerable<SarahTizzard_WEBD3000_MyTunes_MVC.Models.Artist>*@
@model PagedList.IPagedList<SarahTizzard_WEBD3000_MyTunes_MVC.Models.Artist>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Artists</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Artist", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.Name)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ArtistId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArtistId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArtistId })
        </td>
    </tr>
}

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Artist/Index.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.ViewModels.ArtistIndexData
@*@model PagedList.IPagedList<SarahTizzard_WEBD3000_MyTunes_MVC.ViewModels.ArtistIndexData>*@
@using PagedList.Mvc;
@{
    ViewBag.Title = "Artists";
}

<h2>Artists</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Artist", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @*Name*@
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Artists)
{
    string selectedRow = "";
    if (item.ArtistId == ViewBag.ArtistId)
    {
        selectedRow = "success";
    }
    <tr class="@selectedRow">
        @*<td>
            @Html.DisplayFor(modelItem => item.ArtistId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Select", "Index", new { id = item.ArtistId }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.ArtistId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArtistId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArtistId })
        </td>
    </tr>
}

</table>

<div>
    Page @(Model.Artists.PageCount < Model.Artists.PageNumber ? 0 : Model.Artists.PageNumber) of @Model.Artists.PageCount

    @Html.PagedListPager(Model.Artists, page => Url.Action("Index", new { artistPage = page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</div>

@if (Model.Albums != null)
{
    <h3>Albums by selected artist</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>
                Album Title
                @*@Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })*@
            </th>                
        </tr>

            @foreach (var item in Model.Albums)
            {
                string selectedRow = "";
                if (item.AlbumId == ViewBag.AlbumId)
                {
                    selectedRow = "success";
                }
                <tr class="@selectedRow">

                    <td>@Html.ActionLink("Select", "Index", new { albumid = item.AlbumId })</td>

                    <td>
                        @item.Title
                    </td>
                </tr>
            }

        </table>

if (Model.Tracks != null)
{
    <h3>Tracks on selected album</h3>
    <table class="table">
        <tr>
            <th></th>

            <th>
                Track Name
            </th>
        </tr>

        @foreach (var item in Model.Tracks)
        {
            string selectedRow = "";
            if (item.AlbumId == ViewBag.AlbumId)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @item.Name
                </td>
            </tr>
        }

    </table>
}
}