MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Models/Track.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SarahTizzard_WEBD3000_MyTunes_MVC.Models
{
    public class Track
    {
        public int TrackId { get; set; }

        [Required]
        [RegularExpression(@"^.{3,50}$", ErrorMessage = "Track name must be between 3 and 50 characters.")]
        public string Name { get; set; }

        [Required]
        public int? AlbumId { get; set; }

        [Required]
        public int MediaTypeId { get; set; }

        [Required]
        public int? GenreId { get; set; }

        [RegularExpression(@"^.{3,50}$", ErrorMessage = "Composer name must be between 3 and 50 characters.")]
        public string Composer { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{1,9}$", ErrorMessage = "Exceeds maximum length restrictions.")]
        public int Milliseconds { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{1,11}$", ErrorMessage = "Exceeds maximum size restrictions.")]
        public int? Bytes { get; set; }

        [Required]
        [RegularExpression(@"^\d+(\.\d\d)?$", ErrorMessage = "Please use numeric currency format: 0.00")]
        public decimal UnitPrice { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        public virtual Album Album { get; set; }

        public virtual Genre Genre { get; set; }

        public virtual MediaType MediaType { get; set; }
    }
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Controllers/TrackController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SarahTizzard_WEBD3000_MyTunes_MVC.DAL;
using SarahTizzard_WEBD3000_MyTunes_MVC.Models;
using PagedList;
using System.Data.SqlClient;
using System.Data.Entity.Infrastructure;
using System.Threading.Tasks;

namespace SarahTizzard_WEBD3000_MyTunes_MVC.Controllers
{
    public class TrackController : Controller
    {
        private MyTunesContext db = new MyTunesContext();

        // GET: Track
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            
            ViewBag.AlbumSortParm = sortOrder == "Album" ? "album_desc" : "Album";
            ViewBag.GenreSortParm = sortOrder == "Genre" ? "genre_desc" : "Genre";
            ViewBag.MediaSortParm = sortOrder == "Media" ? "media_desc" : "Media";
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
            ViewBag.ComposerSortParm = sortOrder == "Composer" ? "composer_desc" : "Composer";
            ViewBag.TimeSortParm = sortOrder == "Milliseconds" ? "time_desc" : "Milliseconds";
            ViewBag.SizeSortParm = sortOrder == "Bytes" ? "size_desc" : "Bytes";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var tracks = from t in db.Tracks
                         select t;

            if (!String.IsNullOrEmpty(searchString))
            {
                tracks = tracks.Where(t => t.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "album_desc":
                    tracks = tracks.OrderByDescending(t => t.Album.Title);
                    break;
                case "genre_desc":
                    tracks = tracks.OrderByDescending(t => t.Genre.Name);
                    break;
                case "media_desc":
                    tracks = tracks.OrderByDescending(t => t.MediaType.Name);
                    break;
                case "name_desc":
                    tracks = tracks.OrderByDescending(t => t.Name);
                    break;
                case "composer_desc":
                    tracks = tracks.OrderByDescending(t => t.Composer);
                    break;
                case "time_desc":
                    tracks = tracks.OrderByDescending(t => t.Milliseconds);
                    break;
                case "size_desc":
                    tracks = tracks.OrderByDescending(t => t.Bytes);
                    break;
                case "price_desc":
                    tracks = tracks.OrderByDescending(t => t.UnitPrice);
                    break;
                case "Album":
                    tracks = tracks.OrderBy(t => t.Album.Title);
                    break;
                case "Genre":
                    tracks = tracks.OrderBy(t => t.Genre.Name);
                    break;
                case "Media":
                    tracks = tracks.OrderBy(t => t.MediaType.Name);
                    break;
                case "Name":
                    tracks = tracks.OrderBy(t => t.Name);
                    break;
                case "Composer":
                    tracks = tracks.OrderBy(t => t.Composer);
                    break;
                case "Milliseconds":
                    tracks = tracks.OrderBy(t => t.Milliseconds);
                    break;
                case "Bytes":
                    tracks = tracks.OrderBy(t => t.Bytes);
                    break;
                case "Price":
                    tracks = tracks.OrderBy(t => t.UnitPrice);
                    break;
                default:
                    tracks = tracks.OrderBy(t => t.Genre.Name);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(tracks.ToPagedList(pageNumber, pageSize));
            //return View(tracks.ToList());
        }


        // GET: Track/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Track track = db.Tracks.Find(id);
            if (track == null)
            {
                return HttpNotFound();
            }
            return View(track);
        }

        // GET: Track/Create
        public ActionResult Create()
        {
            ViewBag.AlbumId = new SelectList(db.Albums, "AlbumId", "Title");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            ViewBag.MediaTypeId = new SelectList(db.MediaTypes, "MediaTypeId", "Name");
            return View();
        }

        // POST: Track/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice")] Track track)
        {
            try {
                if (ModelState.IsValid)
                {
                    db.Tracks.Add(track);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException  /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");

            }

            ViewBag.AlbumId = new SelectList(db.Albums, "AlbumId", "Title", track.AlbumId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", track.GenreId);
            ViewBag.MediaTypeId = new SelectList(db.MediaTypes, "MediaTypeId", "Name", track.MediaTypeId);
            return View(track);
        }

        // GET: Track/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Track track = db.Tracks.Find(id);
            if (track == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlbumId = new SelectList(db.Albums, "AlbumId", "Title", track.AlbumId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", track.GenreId);
            ViewBag.MediaTypeId = new SelectList(db.MediaTypes, "MediaTypeId", "Name", track.MediaTypeId);
            return View(track);
        }

        // POST: Track/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, byte[] rowVersion)
        {
            string[] fieldsToBind = new string[] { "TrackId","Name", "AlbumId", "MediaTypeId", "GenreId", "Composer", "Milliseconds", "Bytes", "UnitPrice", "RowVersion" };

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var trackToUpdate = await db.Tracks.FindAsync(id);
            if (trackToUpdate == null)
            {
                Track deletedTrack = new Track();
                TryUpdateModel(deletedTrack, fieldsToBind);
                ModelState.AddModelError(string.Empty,
                    "Unable to save changes. The track was deleted by another user.");
                ViewBag.TrackId = new SelectList(db.Tracks, "TrackId", "Name", deletedTrack.TrackId);
                return View(deletedTrack);
            }

            if (TryUpdateModel(trackToUpdate, fieldsToBind))
            {
                try
                {
                    db.Entry(trackToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    await db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var entry = ex.Entries.Single();
                    var clientValues = (Track)entry.Entity;
                    var databaseEntry = entry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError(string.Empty,
                            "Unable to save changes. The track was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Track)databaseEntry.ToObject();

                        if (databaseValues.Name != clientValues.Name)
                            ModelState.AddModelError("Name", "Current value: "
                                + databaseValues.Name);
                        if (databaseValues.AlbumId != clientValues.AlbumId)
                            ModelState.AddModelError("AlbumId", "Current value: "
                                + String.Format("{0:c}", databaseValues.AlbumId));
                        if (databaseValues.MediaTypeId != clientValues.MediaTypeId)
                            ModelState.AddModelError("MediaTypeId", "Current value: "
                                + String.Format("{0:d}", databaseValues.MediaTypeId));

                        if (databaseValues.GenreId != clientValues.GenreId)

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/Create.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Track</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "Album", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediaTypeId, "MediaType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MediaTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MediaTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "Genre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Composer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Composer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Composer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Milliseconds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Milliseconds, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Milliseconds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bytes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bytes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/DBStats.cshtml
@model IEnumerable<SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track>

@{
        ViewBag.Title = "DBStats";
}


<div>
    <h4>Content Statistics</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Total Tracks:
        </dt>

        <dd>
            @ViewBag.TotalTracks
        </dd>

        <dt>
            Total Artists:
        </dt>

        <dd>
            @ViewBag.TotalArtists
        </dd>

        <dt>
            Total Albums:
        </dt>

        <dd>
            @ViewBag.TotalAlbums
        </dd>

        <dt>
            Largest Track:
        </dt>

        <dd>
            @ViewBag.LargestTrack
        </dd>

        <dt>
            Longest Track:
        </dt>

        <dd>
            @ViewBag.LongestTrack
        </dd>


        <dt>
            Genres:
        </dt>
        @foreach(var item in ViewBag.Genres)
        {
            <dd>
                @Html.DisplayFor(modelItem => item)
            </dd>
        }

        <dt>
            Media Types:
        </dt>
        @foreach (var item in ViewBag.MediaTypes)
        {
            <dd>
                @Html.DisplayFor(modelItem => item)
            </dd>
        }

        <dt>
            Media Categories:
        </dt>
        @foreach (var item in ViewBag.MediaTypes)
        {
            <dd>
                @Html.DisplayFor(modelItem => item)
            </dd>
        }
        

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

</div>

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/Delete.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (@ViewBag.ConcurrencyErrorMessage != null)
{
    <p class="error">@ViewBag.ConcurrencyErrorMessage</p>

}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Track</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Milliseconds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Milliseconds)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bytes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.TrackId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/Details.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Milliseconds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Milliseconds)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bytes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrackId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/Edit.cshtml
@model SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Track</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TrackId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediaTypeId, "MediaTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MediaTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MediaTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreId, "GenreId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Composer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Composer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Composer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Milliseconds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Milliseconds, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Milliseconds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bytes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bytes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyTunes_MVC/SarahTizzard_WEBD3000_MyTunes_MVC/Views/Track/Index.cshtml
@*@model IEnumerable<SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track>*@
@model PagedList.IPagedList<SarahTizzard_WEBD3000_MyTunes_MVC.Models.Track>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Tracks</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Track", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>    
        <th>
            @Html.ActionLink("Album", "Index", new { sortOrder = ViewBag.AlbumSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>

        <th>
            @Html.ActionLink("Genre", "Index", new { sortOrder = ViewBag.GenreSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>

        <th>
            @Html.ActionLink("MediaType", "Index", new { sortOrder = ViewBag.MediaSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Composer", "Index", new { sortOrder = ViewBag.ComposerSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Milliseconds", "Index", new { sortOrder = ViewBag.TimeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Bytes", "Index", new { sortOrder = ViewBag.SizeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Album.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MediaType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Composer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Milliseconds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bytes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TrackId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TrackId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TrackId })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))